if ! pgrep -x hyprland > /dev/null; then
  hyprland
fi

source <(fzf --zsh)

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
set -o vi

eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/theme.omp.json)"
eval "$(zoxide init zsh)"

# Zplug
if [[ ! -f ~/.zplug/init.zsh ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"

if ! zplug check --verbose; then
    zplug install
fi

zplug load

# Aliases
alias "ls"="eza -a --icons=always"
alias "ll"="eza -a --icons=always"
alias "l"="eza -a --icons=always"
alias "lt"="eza -a --tree --level=1 --icons=always"
alias "cd"="z"

gp() {
  local message="${1:-Quick Commit}"
  local branch="${2:-main}"

  git add .
  git commit -m "$message"
  git push origin "$branch"
}

